title: "LESSON 4 - Load Balancer + NAT Gateway + Bastion Host"
description: "FoggyKitchen Terraform OCI Course - LESSON 4 - Load Balancer + NAT Gateway + Bastion Host."
stackDescription: "FoggyKitchen Terraform OCI Course - LESSON 4 - Load Balancer + NAT Gateway + Bastion Host."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region
  - webservice_ports
  - bastion_ports

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name 
  - show_advanced 

- title: "Networking Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - VCN-CIDR
  - PrivateSubnet-CIDR
  - LBSubnet-CIDR
  - BastionSubnet-CIDR

- title: "Load Balancer Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - lb_shape
  - flex_lb_min_shape
  - flex_lb_max_shape

- title: "Webserver Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - WebserverShape
  - WebserverFlexShapeOCPUS
  - WebserverFlexShapeMemory
  - instance_os
  - linux_os_version

- title: "Bastion Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - BastionShape
  - BastionFlexShapeOCPUS
  - BastionFlexShapeMemory

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your Webserver"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your Webserver"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain"
    description: "Choose Availability Domain where your Webserver1 & Webserver2 will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  # Optional Configuration

  ComputeCount:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "Webservers Compute Count"
    description: "Number of compute instances to create."

  VCN-CIDR:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the VCN"

  PrivateSubnet-CIDR:
    type: string
    required: false
    default: "10.0.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "WebSubnet CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  PublicSubnet-CIDR:
    type: string
    required: false
    default: "10.0.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "LoadBalancer Subnet CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  BastionSubnet-CIDR:
    type: string
    required: false
    default: "10.0.3.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Bastion Subnet CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  WebserverShape:
    type: oci:core:instanceshape:name
    title: "Webserver Shape"
    description: "Choose a shape for your Webservers"
    default: "VM.Standard.E4.Flex"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  BastionShape:
    type: oci:core:instanceshape:name
    title: "Bastion Shape"
    description: "Choose a shape for your Bastion Server"
    default: "VM.Standard.E4.Flex"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}


  WebserverFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Webserver Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Webserver Shape."
    visible:
      and:
        - or:
          - eq:
            - WebserverShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - WebserverShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - WebserverShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - WebserverShape 
            - "VM.Optimized3.Flex"

  WebserverFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Webserver Memory."
    visible:
      and:
        - or:
          - eq:
            - WebserverShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - WebserverShape
            - "VM.Standard.E4.Flex"
          - eq:
            - WebserverShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - WebserverShape 
            - "VM.Optimized3.Flex"

  BastionFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Bastion Flex Shape OCPUs"
    description: "Choose number of OCPUs for Bastion Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - BastionShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - BastionShape 
            - "VM.Optimized3.Flex"

  BastionFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "Bastion Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Bastion Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - BastionShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - BastionShape
            - "VM.Standard.E4.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - BastionShape 
            - "VM.Optimized3.Flex"


  instance_os:
    type: enum
    required: false
    visible: true
    title: "Instance OS"
    description: "Choose Operating System that determines the operating system for Webserver host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: true
    title: "Instance OS version"
    description: "Choose Operating System version that determines the operating system version for Webserver host."
    default: "8"
    enum:
      - "8"
      - "9"  

  lb_shape:
    type: enum
    title: "Load Balanacer Shape"
    description: "Load Balanacer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LB Flex Max Shape"
    description: "Choose Maximum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  webservice_ports:
    title: "Web Service Ports"
    description: "Web Service Ports"
    type: string
    required: false
    visible: false

  bastion_ports:
    title: "Baston SSH Ports"
    description: "Bastion SSH Ports"
    type: string
    required: false
    visible: false

outputs:

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: string
    visible: true
  
  FoggyKitchenPublicLoadBalancer_Public_IP:
    title: "LoadBalancer Public IP"
    displayText: "LoadBalancer Public IP"
    type: copyableString
    visible: true


